In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv(r"C:\21761A0572\m.CSV")

In [72]:
df

sno  country   age   salary purchased
0    0   france  44.0  72000.0        no
1    1    spain  27.0  48000.0       yes
2    2  germany  30.0  54000.0        no
3    3    spain  38.0  61000.0        no
4    4  germany  40.0      NaN       yes
5    5   france  35.0  58000.0       yes
6    6    spain   NaN  52000.0        no
7    7   france  48.0  79000.0       yes
8    8  germany  50.0  83000.0        no
9    9   france  37.0  67000.0       yes

In [73]:
df.info

<bound method DataFrame.info of    sno  country   age   salary purchased
0    0   france  44.0  72000.0        no
1    1    spain  27.0  48000.0       yes
2    2  germany  30.0  54000.0        no
3    3    spain  38.0  61000.0        no
4    4  germany  40.0      NaN       yes
5    5   france  35.0  58000.0       yes
6    6    spain   NaN  52000.0        no
7    7   france  48.0  79000.0       yes
8    8  germany  50.0  83000.0        no
9    9   france  37.0  67000.0       yes>

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   sno        10 non-null     int64  
 1   country    10 non-null     object 
 2   age        9 non-null      float64
 3   salary     9 non-null      float64
 4   purchased  10 non-null     object 
dtypes: float64(2), int64(1), object(2)
memory usage: 528.0+ bytes


In [97]:
x= df.iloc[:, :-1].values  
  

In [98]:
x

array([[0, 'france', 44.0, 72000.0],
       [1, 'spain', 27.0, 48000.0],
       [2, 'germany', 30.0, 54000.0],
       [3, 'spain', 38.0, 61000.0],
       [4, 'germany', 40.0, nan],
       [5, 'france', 35.0, 58000.0],
       [6, 'spain', nan, 52000.0],
       [7, 'france', 48.0, 79000.0],
       [8, 'germany', 50.0, 83000.0],
       [9, 'france', 37.0, 67000.0]], dtype=object)

In [99]:
from sklearn.impute import SimpleImputer  
imputer= SimpleImputer(missing_values =np.NaN, strategy='mean')  
imputer= imputer.fit(x[:, 2:4])  
x[:, 2:4]= imputer.transform(x[:, 2:4])  
x

array([[0, 'france', 44.0, 72000.0],
       [1, 'spain', 27.0, 48000.0],
       [2, 'germany', 30.0, 54000.0],
       [3, 'spain', 38.0, 61000.0],
       [4, 'germany', 40.0, 63777.77777777778],
       [5, 'france', 35.0, 58000.0],
       [6, 'spain', 38.77777777777778, 52000.0],
       [7, 'france', 48.0, 79000.0],
       [8, 'germany', 50.0, 83000.0],
       [9, 'france', 37.0, 67000.0]], dtype=object)

# 1. handling categorical data 

# using label encoder

In [100]:
from sklearn.preprocessing import LabelEncoder  
label_encoder_x= LabelEncoder()  
x[:, 1]= label_encoder_x.fit_transform(x[:, 1])  

In [101]:
x

array([[0, 0, 44.0, 72000.0],
       [1, 2, 27.0, 48000.0],
       [2, 1, 30.0, 54000.0],
       [3, 2, 38.0, 61000.0],
       [4, 1, 40.0, 63777.77777777778],
       [5, 0, 35.0, 58000.0],
       [6, 2, 38.77777777777778, 52000.0],
       [7, 0, 48.0, 79000.0],
       [8, 1, 50.0, 83000.0],
       [9, 0, 37.0, 67000.0]], dtype=object)

In [102]:
y= df.iloc[:, 4] 
  

In [103]:
y

0     no
1    yes
2     no
3     no
4    yes
5    yes
6     no
7    yes
8     no
9    yes
Name: purchased, dtype: object

In [104]:
labelencoder_y= LabelEncoder()  
y= labelencoder_y.fit_transform(y)  

In [105]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# using one hot encoder dummies

In [106]:
from sklearn.preprocessing import OneHotEncoder


In [107]:
ohe=pd.get_dummies(df['country'])


In [108]:
ohe

france  germany  spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0
6       0        0      1
7       1        0      0
8       0        1      0
9       1        0      0

In [109]:
from sklearn.preprocessing import OneHotEncoder
oy=OneHotEncoder()
oy.fit_transform(df.purchased.values.reshape(-1,1)).toarray()

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

# 2.train & test

In [115]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)  

In [116]:
x_test

array([[2, 1, 30.0, 54000.0],
       [8, 1, 50.0, 83000.0]], dtype=object)

In [117]:
x_train

array([[4, 1, 40.0, 63777.77777777778],
       [9, 0, 37.0, 67000.0],
       [1, 2, 27.0, 48000.0],
       [6, 2, 38.77777777777778, 52000.0],
       [7, 0, 48.0, 79000.0],
       [3, 2, 38.0, 61000.0],
       [0, 0, 44.0, 72000.0],
       [5, 0, 35.0, 58000.0]], dtype=object)

In [118]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [119]:
y_test

array([0, 0])

# 3.scaling the features

In [120]:
from sklearn.preprocessing import StandardScaler  
g = StandardScaler()  
x_train= g.fit_transform(x_train)  
x_test= g.transform(x_test)  

In [121]:
x_train

array([[-0.13271219,  0.13483997,  0.26306757,  0.12381479],
       [ 1.63678363, -0.94387981, -0.25350148,  0.46175632],
       [-1.19440968,  1.21355975, -1.97539832, -1.53093341],
       [ 0.57508614,  1.21355975,  0.05261351, -1.11141978],
       [ 0.92898531, -0.94387981,  1.64058505,  1.7202972 ],
       [-0.48661135,  1.21355975, -0.0813118 , -0.16751412],
       [-1.54830884, -0.94387981,  0.95182631,  0.98614835],
       [ 0.22118698, -0.94387981, -0.59788085, -0.48214934]])

In [122]:
x_test

array([[-0.84051051,  0.13483997, -1.45882927, -0.90166297],
       [ 1.28288447,  0.13483997,  1.98496442,  2.13981082]])

In [123]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])